export const ADD_STOP = 'ADD_STOP_COMPLETED';
export const ADD_STOP_STARTED = 'ADD_STOP_COMPLETED';
export const ADD_STOP_COMPLETED = 'ADD_STOP_COMPLETED';
export const ADD_STOP_FAILED = 'ADD_STOP_COMPLETED';

export const DELETE_STOP = 'DELETE_STOP';
